version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: car_rental_api
    depends_on:
      - db
    env_file: .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
      alembic upgrade head &&
      python app/seed.py &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  pgdata:
